export { default as Hero } from "./Hero/Hero";
export { default as Card } from "./Card/Card";
export { default as Modal } from "./Modal/Modal";
export { default as Email } from "./Email/Email";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as Marquee } from "./Marquee/Marquee";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as TechCard } from "./TechCard/TechCard";
export { default as Showcase } from "./Showcase/Showcase";
export { default as TimeLine } from "./TimeLine/TimeLine";
export { default as ProjectHero } from "./ProjectHero/ProjectHero";
export { default as TimeLineData } from "./TimeLineData/TimeLineData";
export { default as Technologies } from "./Technologies/Technologies";
export { default as AboutDetails } from "./AboutDetails/AboutDetails";
export { default as MitionAnimate } from "./MitionAnimate/MitionAnimate";
export { default as ProjectDtails } from "./ProjectDtails/ProjectDtails";
export { default as ContactDetails } from "./ContactDetails/ContactDetails";

