export type { default as INavLink } from "./NavLinkInterface";
export type { default as ITechIcons } from "./TeckskillsInterface";
export type { default as IHomeMainObj } from "./HomeInterface";
export type { default as IDescription } from "./Shareinterface";
export type { default as IProjects } from "./ProjectsInterface";
export type { default as IProjectHero } from "./projectHeroInterface";
export type { default as IAboutMainObj } from "./AboutInterface";
export type { default as IMarqueeIcons } from "./MarqueeIconsInterface";
export type { default as IQualification } from "./QualificationInterfaces";
